name: "eamxx-format"

# if .{cpp,hpp} files are touched in a PR, lint them!

on:
  pull_request:
    branches: ["master"]
    paths:
      - 'components/eamxx/**/*.cpp'
      - 'components/eamxx/**/*.hpp'

  # Manual run
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  clang-format-linter:
    # FIXME: change repo!!!
    if: ${{ github.repository == 'mjschmidt271/E3SM' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: tj-actions/changed-files@v46
      id: changed-files
      with:
        files: 'components/eamxx/**/*.{cpp,hpp}'
        separator: " "
    # 1. runs clang-format on the files changed by this PR, and returns pass/fail
    #    error code.
    # 2. prints the diff to screen (action log), comparing to the changes
    #    that *would* be made
    # 3. the E3SM-Project fork of DoozyX/clang-format-lint-action@v0.20
    #    adds a Step summary to the workflow page, and, on failure, lists the
    #    files that fail the clang-format test
    - uses: mjschmidt271/clang-format-lint-action@f2ec09454bde102a03bd88b814db510fa865cc6e
      with:
        source: ${{ steps.changed-files.outputs.all_changed_files }}
        exclude: ''
        extensions: 'hpp,cpp'
        clangFormatVersion: 14
        style: 'file:components/eamxx/.clang-format'
        inplace: True
        write_summary: False
    - name: diff format changes
      run: git diff >> "components/eamxx/clang-format-patch.diff"
    - name: reset to re-run clang-format
      run: git reset --hard HEAD
    - uses: mjschmidt271/clang-format-lint-action@f2ec09454bde102a03bd88b814db510fa865cc6e
      with:
        source: ${{ steps.changed-files.outputs.all_changed_files }}
        exclude: ''
        extensions: 'hpp,cpp'
        clangFormatVersion: 14
        style: 'file:components/eamxx/.clang-format'
        inplace: False
        write_summary: True
    - name: upload diff patch
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: clang-format-patch_${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}.diff
        path: |
          components/eamxx/clang-format-patch.diff
      env:
        NODE_EXTRA_CA_CERTS: ${{ env.NODE_EXTRA_CA_CERTS }}
